FROM {{ source }}:{{ version }}-{{ variant }}

MAINTAINER {{ maintainer }}

# Install custom extensions
{% if variant == 'alpine' %}
RUN apk upgrade --update && \
    apk add --no-cache git openssh zip make yarn
{% else %}
RUN apt-get update && apt-get install -y \
    make curl yarn wget zip git
{% endif %}
